version: 1.1.10.{build}

image:
  - Visual Studio 2019
  - Ubuntu2004

configuration:
  - Release

platform:
  - x64  

install:
  - sh: sudo apt update
  - sh: sudo apt install -y gcc-multilib g++-multilib
  - sh: sudo apt install -y uuid-dev libx11-dev libxrandr-dev libpng-dev
  - sh: sudo apt install -y libxtst-dev libxtst-dev:i386  
  
  - cmd: appveyor DownloadFile https://dl.bintray.com/boostorg/release/1.74.0/source/boost_1_74_0.tar.gz
  - cmd: tar xzf boost_1_74_0.tar.gz
  - cmd: cd boost_1_74_0
  - cmd: bootstrap.bat
  - cmd: b2.exe toolset=msvc link=static threading=multi runtime-link=static release stage
  - cmd: cd ..

init:
  - cmd: cmake --version
  - cmd: msbuild /version

before_build:
  - cmd: echo %APPVEYOR_BUILD_VERSION% > "version.txt"
  - sh: echo ${APPVEYOR_BUILD_VERSION} > "version.txt"
  - sh: echo "#define VERSION_FULL " ${APPVEYOR_BUILD_VERSION} > "version.h"

build_script:
  - cmd: Powershell.exe -File manifest.ps1 -Project VanessaExt -Version %APPVEYOR_BUILD_VERSION%

  - cmd: mkdir build32
  - cmd: cd build32
  - cmd: cmake .. -A Win32 -DMySuffix2=32
  - cmd: cmake --build . --config Release
  - cmd: cd ..
  - cmd: mkdir build64
  - cmd: cd build64
  - cmd: cmake .. -A x64 -DMySuffix2=64
  - cmd: cmake --build . --config Release
  - cmd: cd ..
  - cmd: copy bin\Release\libVanessaExtWin??.dll .

  - sh: mkdir build32
  - sh: cd build32
  - sh: cmake -D CMAKE_BUILD_TYPE:STRING=Release -D TARGET_PLATFORM_32:BOOL=ON --build ..
  - sh: cmake --build .
  - sh: cd ..
  - sh: mkdir build64
  - sh: cd build64
  - sh: cmake -D CMAKE_BUILD_TYPE:STRING=Release -D TARGET_PLATFORM_32:BOOL=OFF --build ..
  - sh: cmake --build .
  - sh: cd ..
  - sh: cp bin/libVanessaExtLin??.so .

after_build:
  - cmd: 7z a VanessaExt.zip libVanessaExtWin??.dll manifest.xml version.txt version.h
  - sh: 7z a VanessaExt.zip libVanessaExtLin??.so version.txt version.h

artifacts:
  - path: VanessaExt.zip
    name: VanessaExt
