version: 1.2.1.{build}

configuration: Release
platform: x64

branches:
  only:
    - develop

skip_branch_with_pr: true

environment:
  global:
    URL_1CV8T:
      secure: z47uplaqZaQ0ZkroXy0GP00nv6ACPwovtb+EjfPgpS1UVp1iZSkRJGz8uOWarUXi
    API_TOKEN:
      secure: 85XpT8I1bxRTZaiIA+co0b5GS05J2VOn7PzunkYlL40=

  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
      job_name: Linux
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      job_depends_on: Linux
      job_name: Windows

install:
  - git clone -q --branch=master https://github.com/libgit2/libgit2.git libgit2-1.0.1
  - cd libgit2-1.0.1
  - git checkout -b version v1.0.1
  - cd ..

  - git clone -q --branch=master https://github.com/libssh2/libssh2.git libssh2-1.9.0
  - cd libssh2-1.9.0
  - git checkout -b version libssh2-1.9.0
  - cd ..

  - sh: sudo dpkg --add-architecture i386
  - sh: sudo apt -qq update
  - sh: sudo apt -qq -y install
      uuid-dev uuid-dev:i386
      libx11-dev libx11-dev:i386
      libxtst-dev libxtst-dev:i386
      libxrandr-dev libxrandr-dev:i386
      libpng-dev libpng-dev:i386
      libssl-dev libssl-dev:i386
      gcc-multilib g++-multilib

  - cmd: appveyor DownloadFile https://dl.bintray.com/boostorg/release/1.74.0/source/boost_1_74_0.tar.gz
  - cmd: tar xzf boost_1_74_0.tar.gz
  - cmd: cd boost_1_74_0
  - cmd: bootstrap.bat
  - cmd: b2.exe toolset=msvc link=static threading=multi runtime-link=static release stage --with-regex --with-date_time
  - cmd: cd ..

init:
  - cmd: cmake --version
  - cmd: msbuild /version
  - cmd: echo.

build_script:
  - sh: echo "#define VERSION_FULL " ${APPVEYOR_BUILD_VERSION} > "version.h"
  - cmd: Powershell.exe -File manifest.ps1 -Project VanessaExt -Version %APPVEYOR_BUILD_VERSION%

  - mkdir build32
  - cd build32
  - sh: cmake -D CMAKE_BUILD_TYPE:STRING=Release -D TARGET_PLATFORM_32:BOOL=ON --build ..
  - cmd: cmake .. -A Win32 -DMySuffix2=32
  - cmake --build . --config Release
  - cd ..

  - mkdir build64
  - cd build64
  - sh: cmake -D CMAKE_BUILD_TYPE:STRING=Release -D TARGET_PLATFORM_32:BOOL=OFF --build ..
  - cmd: cmake .. -A x64 -DMySuffix2=64
  - cmake --build . --config Release
  - cd ..

  - sh: cp bin/libVanessaExtLin??.so .
  - sh: 7z a VanessaExt.zip libVanessaExtLin??.so
  - cmd: copy bin\Release\libVanessaExtWin??.dll .
  - cmd: Powershell.exe -File appveyor.ps1

for:
  - matrix:
      only:
        - job_name: Linux
    artifacts:
      - path: VanessaExt.zip
        name: VanessaExt

  - matrix:
      only:
        - job_name: Windows

    cache: 1cv8t.7z

    after_build:
      - 7z x 1cv8t.7z
      - mkdir database
      - bin\1cv8t.exe CREATEINFOBASE File=%CD%/database
      - bin\1cv8t.exe DESIGNER /F %CD%/database /LoadConfigFromFiles %CD%/config /UpdateDBCfg
      - bin\1cv8t.exe DESIGNER /F %CD%/database /LoadExternalDataProcessorOrReportFromFiles Example.xml VanessaExt.epf /Out example.log
      - bin\1cv8ct.exe ENTERPRISE /F %CD%/database /C VanessaExt.epf

    artifacts:
      - path: AddIn.zip
        name: AddIn

      - path: VanessaExt.epf
        name: VanessaExt

      - path: autotest.log
        name: autotest log

      - path: example.log
        name: example log

    deploy:
      - provider: GitHub
        auth_token:
          secure: v7P89NQ2I5+WGNNdhpFrZEt6OCTPf8A8VSC5rttZMXh3DJ2fTChNEjZ1Wvm3kfBt
        repository: lintest/VanessaExt
        artifact: AddIn.zip, VanessaExt.epf
        draft: true
        prerelease: true
        force_update: true
        on:
          branch: master
