version: 1.2.1.{build}

image:
  - Visual Studio 2019
  - Ubuntu1804

configuration:
  - Release

platform:
  - x64

install:
  - git clone -q --branch=master https://github.com/libgit2/libgit2.git libgit2-1.0.1
  - cd libgit2-1.0.1
  - git checkout -b version v1.0.1
  - cd ..

  - git clone -q --branch=master https://github.com/libssh2/libssh2.git libssh2-1.9.0
  - cd libssh2-1.9.0
  - git checkout -b version libssh2-1.9.0
  - cd ..

  - sh: sudo dpkg --add-architecture i386
  - sh: sudo apt -qq update
  - sh: sudo apt -qq -y install uuid-dev libx11-dev libxrandr-dev libpng-dev
  - sh: sudo apt -qq -y install libxtst-dev libxtst-dev:i386 libssl-dev libssl-dev:i386
  - sh: sudo apt -qq -y install gcc-multilib g++-multilib

  - cmd: appveyor DownloadFile https://dl.bintray.com/boostorg/release/1.74.0/source/boost_1_74_0.tar.gz
  - cmd: tar xzf boost_1_74_0.tar.gz
  - cmd: cd boost_1_74_0
  - cmd: bootstrap.bat
  - cmd: b2.exe toolset=msvc link=static threading=multi runtime-link=static release stage
  - cmd: cd ..

init:
  - cmd: cmake --version
  - cmd: msbuild /version
  - cmd: echo.

before_build:
  - cmd: echo %APPVEYOR_BUILD_VERSION% > "version.txt"
  - sh: echo ${APPVEYOR_BUILD_VERSION} > "version.txt"
  - sh: echo "#define VERSION_FULL " ${APPVEYOR_BUILD_VERSION} > "version.h"

build_script:
  - cmd: Powershell.exe -File manifest.ps1 -Project VanessaExt -Version %APPVEYOR_BUILD_VERSION%

  - mkdir build32
  - cd build32
  - sh: cmake -D CMAKE_BUILD_TYPE:STRING=Release -D TARGET_PLATFORM_32:BOOL=ON --build ..
  - cmd: cmake .. -A Win32 -DMySuffix2=32
  - cmd: cmake --build . --config Release
  - cd ..

  - mkdir build64
  - cd build64
  - sh: cmake -D CMAKE_BUILD_TYPE:STRING=Release -D TARGET_PLATFORM_32:BOOL=OFF --build ..
  - cmd: cmake .. -A x64 -DMySuffix2=64
  - cmake --build . --config Release
  - cd ..

  - cmd: copy bin\Release\libVanessaExtWin??.dll .
  - sh: cp bin/libVanessaExtLin??.so .

after_build:
  - cmd: 7z a VanessaExt.zip libVanessaExtWin??.* manifest.xml version.txt version.h
  - sh: 7z a VanessaExt.zip libVanessaExtLin??.so version.txt version.h

artifacts:
  - path: VanessaExt.zip
    name: VanessaExt
